### ISSUE TITLE
метод $vk->request()->upload(...) не существует

### ISSUE THREAD

**Issue by joker2620** [VKCOM/vk-php-sdk#16]
PHP говорит что не существует request().
В классе VK\Client\VKApiClient нет такой функции.

![image](https://user-images.githubusercontent.com/21163205/37558201-747a5cac-2a21-11e8-8e05-848bb88477d6.png)

**Comment by bupy7** [comment]
Наверно, потому, что его нет. Ba-dum-tsss...

**Comment by Vadimushka** [comment]
ну на сайте есть, в sdk нет
