### ISSUE TITLE
Баги

### ISSUE THREAD

**Issue by popcorn2d** [VKCOM/vk-php-sdk#18]
Я кшн извиняюсь, но столько кусков не рабочего кода я еще не видел. Зачем вы используете приват константы в классах? Вылетает ошибка, пришлось в ручную убирать их из файлов + в конструкторе уберите ?, тоже вылетает ошибка.
И переделайте документацию, чтобы вызвать $vk = new VKApiClient(); нужно прописать сначала use VK\Client\VKApiClient;

**Comment by bupy7** [comment]
@popcorn2d версия PHP должна быть >= 7.1. Это указано в первом пункте. Константы в конструкторе поддерживаются PHP с версии 5.6. Устанавливая пакет через Composer, а не бабушкиным способом скачивая архив репозитория, Вы бы увидели информацию об ошибке, что Ваша версия PHP ниже, чем требуется для работы этого расширения.
