### ISSUE TITLE
SSL certificate problem

### ISSUE THREAD

**Issue by wumvi** [VKCOM/vk-php-sdk#20]
Проблема с ssl сертификатом

Trace
```
Fatal error: Uncaught VK\Exceptions\VKClientException: VK\TransportClient\TransportRequestException: Failed curl request. Curl error 60: SSL certificate problem: self signed certificate in certificate chain. in F:\Project\vkcom\vendor\vkcom\vk-php-sdk\src\VK\TransportClient\Curl\CurlHttpClient.php:115
```

решить можно поправив код
vendor\vkcom\vk-php-sdk\src\VK\TransportClient\Curl\CurlHttpClient.php:40

```
    public function post(string $url, ?array $payload = null): TransportClientResponse {
        return $this->sendRequest($url, array(
            CURLOPT_POST       => 1,
            CURLOPT_POSTFIELDS => $payload,
            CURLOPT_SSL_VERIFYHOST => 0, // new 
            CURLOPT_SSL_VERIFYPEER => 0, // new
        ));
    }
```

или добавить сетер на доп. параметры для curl

PHP 7.1.11 (cli) (built: Oct 25 2017 21:07:06) ( NTS MSVC14 (Visual C++ 2015) x86 )
Zend Engine v3.1.0, Xdebug v2.6.0, Curl 7.56
Windows 10

**Comment by joker2620** [comment]
Установите сертификат в настройках php.ini (делал так в 7.1.3)

![image](https://user-images.githubusercontent.com/21163205/39020005-0173ba78-4434-11e8-9f03-25f9276c3069.png)

[cacert.zip](https://github.com/VKCOM/vk-php-sdk/files/1929877/cacert.zip)

**Comment by wumvi** [comment]
@joker2620 спасибо
