### ISSUE TITLE
Ошибка в функции getHttpStatus()

### ISSUE THREAD

**Issue by joker2620** [VKCOM/vk-php-sdk#27]
Ошибка при получении заголовка в функции: 
`VK\TransportClient\Curl\CurlHttpClient->getHttpStatus(string $raw_response_header)`:

Запрос:
```
HTTP/1.1 200 OK
Date: Thu, 19 Apr 2018 21:31:58 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Server: awex
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Request-ID: 36f31b17b1bf427188a0662b182b8c3f
```
Ответ:
```
<br />
<b>Notice</b>:  Undefined offset: 1 in <b>.../vendor/vkcom/vk-php-sdk/src/VK/TransportClient/Curl/CurlHttpClient.php</b> on line <b>188</b><br />
ok
```
Запрос сделан через CallBack API.
![image](https://user-images.githubusercontent.com/21163205/39019778-2022b10a-4433-11e8-91a1-72e648e964d0.png)

Для справки, запускал так:
![image](https://user-images.githubusercontent.com/21163205/39020328-20e20c1a-4435-11e8-938a-2a0372295eed.png)

**Comment by demyashev** [comment]
Как решилось?

**Comment by khromoff** [comment]
Проблема в том, что от сервера приходит "HTTP/2 200", '|HTTP/\d\.\d\s+(\d+)\s+.*|'  такое, разумеется, не матчит и в $match[1] ничего нет. Решение тут одно, править регэксп.
