### ISSUE TITLE
VK\Exceptions\Api\VKApiAccessException Access denied: no access to call this method

### ISSUE THREAD

**Issue by widg** [VKCOM/vk-php-sdk#52]
Standalone-приложение. Не получается опубликовать ни картинку ни просто текст на стене группы. 
`$data = array( 
                "owner_id" => "-" . strval($group),
                "message" => $text,
                "form_group" => 1,
                "attachments" => (!empty($attachments) ? $attachments : ""),
            );
return $vk->wall()->post($access_token, $data);`

`"тут access_token"
array:4 [▼
  "owner_id" => "-172101050"
  "message" => "Test"
  "form_group" => 1
  "attachments" => "photo117898960_456239041,"
]`

**Comment by JD99** [comment]
у меня та же беда

**Comment by Mobyman** [comment]
Добрый день! Я бы порекомендовал проверить то, что токен получен с правами wall, как указано в документации.

**Comment by JD99** [comment]
благодарю, проблема была в правах на wall.post. разрешение теперь надо у вк просить на постинг

**Comment by widg** [comment]
Хотя бы написали хоть где нибудь, описание апи просто ужасное, даже на русском ничего не понятно!
