### ISSUE TITLE
Keyboard format is invalid: keyboard should be array

### ISSUE THREAD

**Issue by scientistnik** [VKCOM/vk-php-sdk#62]
Пытаюсь создать клавиатуру. Получаю сообщение об ошибке, мол массив надо передавать. Но я передаю массив. Однако сообщением ранее, видимо, происходит преобразование в строку. 

```php
#!/usr/bin/env php

<?php

require "vendor/autoload.php";
use VK\Client\VKApiClient;
use VK\OAuth\VKOAuth;
use VK\OAuth\VKOAuthDisplay;
use VK\OAuth\VKOAuthResponseType;
use VK\OAuth\Scopes\VKOAuthUserScope;

$access_token = "secretToken";

$vk = new VKApiClient();

$response = $vk->messages()->send($access_token, [
  'user_id' => 31587373,
  'random_id' => 123132,
  'message' => "Hello in code",
  'keyboard' => ['one_time' => false, 'buttons' => []]
]);

print_r($response);

```

```php
PHP Notice:  Array to string conversion in ... vkapi/vendor/vkcom/vk-php-sdk/src/VK/Client/VKApiRequest.php on line 152
PHP Fatal error:  Uncaught VK\Exceptions\VKApiException: Keyboard format is invalid: keyboard should be array in ... vkapi/vendor/vkcom/vk-php-sdk/src/VK/Exceptions/Api/ExceptionMapper.php:90
```

Что я делаю не так? Или это баг?

**Comment by xISRAPILx** [comment]
'keyboard' => json_encode(['one_time' => false, 'buttons' => []])

Учитесь пользоваться переводчиком :)

**Comment by scientistnik** [comment]
> 'keyboard' => json_encode(['one_time' => false, 'buttons' => []])

Да, спасибо. Разобрался уже. На странице документации можно послать тестовый запрос с кнопками.
>Учитесь пользоваться переводчиком :)

всмысле?) json_encode?)

**Comment by xISRAPILx** [comment]
@scientistnik  Array to string conversion

А вообще, возьмите этот [классик ](https://gist.github.com/xISRAPILx/5087fd787ec3499a964b1b4307e78401):3
