### ISSUE TITLE
Конвертация объектов keyboard и template

### ISSUE THREAD

**Issue by n0tm** [VKCOM/vk-php-sdk#80]
Добрый вечер! Я пользуюсь библиотекой vk php sdk очень давно, я написал большое кол-во проектов связанных с ботами и с использованием api вконтакте. Мои коллеги и я сам столкнулся с тем, что конструировать объекты клавиатур или недавно появившихся темплейтов без библиотеки или какой-то тулзы довольно сложно. Не так давно я выложил свою библиотеку по конструированию таких объектов (https://github.com/Sally-Framework/vk-keyboard). 

В связи с этим я хотел задать вопрос. Могу ли я адаптировать свою библиотеку в вашу php sdk, если вы сочтёте её приемлемой?

**Comment by Mobyman** [comment]
Добрый вечер! Да, конечно, однако часть её является автогенерированной, поэтому прямиком из pull-request'а ее подмержить нельзя. 

Но если вы создадите PR, мы сможем актуализировать генератор в соотвествии с вашими изменениями и обновить официальную библиотеку.

**Comment by n0tm** [comment]
Благодарю, закрываю issue)
