### ISSUE TITLE
Сответствие стандарта PSR-4

### ISSUE THREAD

**Issue by MixJay** [VKCOM/vk-php-sdk#99]
При установке VK PHP SDK при помощи composer для фреймворка Laravel 8, консоль PhpStorm наполняется ошибками, сообщая, что данные классы не соответствуют стандарту PSR-4 и поэтому не может быть произведена оптимизация автозагрузки.

Классы, на которые ругается консоль:
VK\Actions\Enum\GroupsAccess
VK\Actions\Enum\GroupsAgeLimits
VK\Actions\Enum\GroupsAudio
VK\Actions\Enum\GroupsDocs
VK\Actions\Enum\GroupsMarketCurrency
VK\Actions\Enum\GroupsPhotos
VK\Actions\Enum\GroupsRole
VK\Actions\Enum\GroupsSubject
VK\Actions\Enum\GroupsTopics
VK\Actions\Enum\GroupsVideo
VK\Actions\Enum\GroupsWall
VK\Actions\Enum\GroupsWiki
VK\Actions\Enum\GroupsWorkInfoStatus
VK\Actions\Enum\StoriesLinkText

**Comment by semivan** [comment]
Symfony 4, такая же проблема

**Comment by wnull** [comment]
Если для кого-то эта проблема остается актуальной, то можете попробовать использовать ветку [форка](https://github.com/rusan/vk-php-sdk), где были исправлены эти неймспейсы для PSR-4.

**Comment by aotd1** [comment]
Fixed in [5.131.0](https://github.com/VKCOM/vk-php-sdk/releases/tag/5.131.0)
